# Test Utilities Package - Shared testing framework

name = "luau_lint/test_utils"
version = "0.1.0"
description = "Shared testing utilities for luau-lint packages"
license = "MIT"
authors = ["Christopher Buss <christopher.buss+github@protonmail.com>"]
repository = "https://github.com/christopher-buss/luau-lint"

# Runtime targets
[target]
environment = "luau"
lib = "src/init.luau"

includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*.luau"]

# Dependencies
[dependencies]
# External dependencies will be added when valid Pesde packages are available

# This package provides testing utilities, so it might need some test frameworks
# The "tiniest" framework is included in src/ already
